
'use strict';
const $=id=>document.getElementById(id), key=s=>String(s).trim().toLowerCase().replace(/\s+/g,' '), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const seed=JSON.parse($('seed').textContent), storageKey='sonoran-dashboard-'+seed.exportId;
let data=structuredClone(seed),editing=false,filter='all',pendingCSV=null,logoDraft='',timer;
function validate(v){if(!v||v.format!==1||!Array.isArray(v.members)||!Array.isArray(v.entries)||!Array.isArray(v.shifts)||!Array.isArray(v.review)||!v.design)throw Error('Not a dashboard backup.');const text=(s,max=300)=>typeof s==='string'&&s.length<=max;const entry=e=>e&&text(e.name,100)&&e.name.trim()&&text(e.team)&&text(e.category)&&text(e.date);if(v.members.length>5000||v.entries.length>30000||v.shifts.length>1000||v.review.length>30000)throw Error('Backup is too large.');if(!v.members.every(m=>text(m.name,100)&&m.name.trim()&&m.id===key(m.name)&&['none','recorded','complete'].includes(m.volunteer)&&text(m.note,1000))||new Set(v.members.map(m=>m.id)).size!==v.members.length||!v.entries.every(entry)||!v.review.every(entry))throw Error('Invalid rider data.');if(!v.shifts.every(s=>text(s.id)&&text(s.title,100)&&text(s.time,100)&&Number.isInteger(s.capacity)&&s.capacity>0&&s.capacity<=500&&Array.isArray(s.members)&&s.members.length<=s.capacity&&new Set(s.members).size===s.members.length&&s.members.every(id=>v.members.some(m=>m.id===id)))||new Set(v.shifts.map(s=>s.id)).size!==v.shifts.length)throw Error('Invalid volunteer shifts.');for(const f of ['brand','brandSubtitle','heading','description','rosterHeading','rosterDescription','footer'])if(!text(v.design[f]))throw Error('Invalid design text.');for(const f of ['headerColor','accentColor','backgroundColor'])if(!/^#[0-9a-f]{6}$/i.test(v.design[f]))throw Error('Invalid color.');if(typeof v.design.logo!=='string'||v.design.logo.length>1500000||(v.design.logo&&!/^data:image\/(png|jpeg|webp);base64,[a-z0-9+/=]+$/i.test(v.design.logo)))throw Error('Invalid embedded logo.');if(!text(v.source,500))throw Error('Invalid source.');return v;}
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('toast').hidden=true,5000);}
function save(){if(!officer||saving)return;dirty=true;render();}
function contrast(hex){const rgb=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2]>.179?'#000000':'#ffffff';}
function entries(m){return data.entries.filter(e=>key(e.name)===m.id);}function assigned(m){return data.shifts.filter(s=>s.members.includes(m.id));}
function render(){const d=data.design;document.title=d.brand+' • '+d.heading;for(const e of document.querySelectorAll('[data-design]'))e.textContent=d[e.dataset.design];for(const [v,f] of [['--navy','headerColor'],['--accent','accentColor'],['--bg','backgroundColor']])document.documentElement.style.setProperty(v,d[f]);document.documentElement.style.setProperty('--headerText',contrast(d.headerColor));document.documentElement.style.setProperty('--accentText',contrast(d.accentColor));$('logo').hidden=!d.logo;if(d.logo)$('logo').src=d.logo;else $('logo').removeAttribute('src');document.querySelectorAll('.editorOnly').forEach(e=>e.hidden=!editing);$('editToggle').textContent=editing?'Close officer tools':'Open officer tools';const registered=data.members.filter(m=>entries(m).length).length,volunteers=data.members.filter(m=>m.volunteer!=='none').length,attention=data.members.filter(m=>!entries(m).length||m.volunteer==='none').length;$('stats').innerHTML=[[data.members.length,'Team riders','Full officer roster'],[registered,'Registered','Matched to BikeReg entries'],[volunteers,'Volunteer records','Recorded or completed'],[attention,'Need attention','Registration or volunteering']].map(([n,l,s])=>'<div class="stat"><div class="eyebrow">'+l+'</div><div class="number">'+n+'</div><small>'+s+'</small></div>').join('');renderRoster();renderShifts();$('source').textContent=data.source+' · '+data.entries.length+' race entries. Registration reflects the last successful sync; GitHub checks about every 15 minutes.';$('reviewPanel').hidden=!editing||!data.review.length;$('review').innerHTML=data.review.map((e,i)=>'<div class="review row"><div style="flex:1"><strong>'+esc(e.name)+'</strong><p>'+esc(e.team)+' · '+esc(e.category)+'</p></div><button data-accept="'+i+'">Include</button><button data-reject="'+i+'">Exclude</button></div>').join('');updateControls();}
function renderRoster(){const list=data.members.filter(m=>key(m.name).includes(key($('search').value))).filter(m=>filter==='all'||filter==='attention'&&(!entries(m).length||m.volunteer==='none')||filter==='registration'&&!entries(m).length||filter==='volunteer'&&m.volunteer==='none');$('roster').innerHTML=list.map(m=>{const es=entries(m),ss=assigned(m),done=m.volunteer!=='none',status=!es.length?'Needs registration':!done?(ss.length?'Shift assigned':'Needs volunteer'):'All good';return '<tr><td><div class="rider"><span class="initials">'+esc(m.name.split(' ').map(p=>p[0]).slice(0,2).join(''))+'</span><div><strong>'+esc(m.name)+'</strong><details><summary>Race entries ('+es.length+')</summary>'+es.map(e=>'<p class="hint">'+esc(e.category)+'</p>').join('')+'</details>'+(editing?'<input class="note" data-note="'+esc(m.id)+'" aria-label="Note for '+esc(m.name)+'" maxlength="1000" placeholder="Team note (public)" value="'+esc(m.note)+'">':m.note?'<p class="hint">'+esc(m.note)+'</p>':'')+'</div></div></td><td><span class="badge '+(es.length?'':'bad')+'">'+(es.length?'✓ Registered':'Not registered')+'</span></td><td>'+(editing?'<select data-vol="'+esc(m.id)+'" aria-label="Volunteer status for '+esc(m.name)+'">'+[['none','Not completed'],['recorded','Recorded in Excel'],['complete','Completed']].map(([v,l])=>'<option value="'+v+'" '+(m.volunteer===v?'selected':'')+'>'+l+'</option>').join('')+'</select>':'<span class="badge '+(done?'':'neutral')+'">'+({none:'Not completed',recorded:'Recorded in Excel',complete:'Completed'}[m.volunteer])+'</span>')+ss.map(s=>'<p class="hint">'+esc(s.title)+' · '+esc(s.time)+'</p>').join('')+'</td><td><span class="badge '+(status==='All good'?'':'neutral')+'">'+status+'</span></td></tr>';}).join('')||'<tr><td colspan="4" class="empty">No riders match this filter.</td></tr>';}
function renderShifts(){$('shifts').innerHTML=data.shifts.map(s=>'<article class="shift"><div class="row" style="justify-content:space-between"><h3>'+esc(s.title)+'</h3><span class="badge neutral">'+s.members.length+' / '+s.capacity+'</span></div><p>'+esc(s.time)+'</p><ul>'+s.members.map(id=>'<li><span>'+esc(data.members.find(m=>m.id===id)?.name||id)+'</span>'+(editing?'<button data-remove="'+esc(id)+'" data-shift="'+esc(s.id)+'" aria-label="Remove '+esc(id)+' from shift">×</button>':'')+'</li>').join('')+'</ul>'+(editing?'<select data-assign="'+esc(s.id)+'" aria-label="Assign volunteer to '+esc(s.title)+'" '+(s.members.length>=s.capacity?'disabled':'')+'><option value="">'+(s.members.length>=s.capacity?'Shift is full':'Assign a rider…')+'</option>'+data.members.filter(m=>!s.members.includes(m.id)).map(m=>'<option value="'+esc(m.id)+'">'+esc(m.name)+'</option>').join('')+'</select><p><button class="quiet" data-delete-shift="'+esc(s.id)+'">Delete shift</button></p>':'')+'</article>').join('')||'<div class="empty">No shifts yet. Officers can create shifts and assign team members.</div>';}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.close)$(b.dataset.close).close();if(b.dataset.filter){filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(t=>t.classList.toggle('active',t===b));renderRoster();}if(!editing)return;if(b.dataset.remove){const s=data.shifts.find(s=>s.id===b.dataset.shift);s.members=s.members.filter(id=>id!==b.dataset.remove);save();}if(b.dataset.deleteShift&&confirm('Delete this shift and its assignments?')){data.shifts=data.shifts.filter(s=>s.id!==b.dataset.deleteShift);save();}if(b.dataset.accept!==undefined){const e=data.review.splice(Number(b.dataset.accept),1)[0];data.matchDecisions??={};data.matchDecisions[decisionKey(e)]='include';data.entries.push(e);addMember(e.name);save();}if(b.dataset.reject!==undefined){const e=data.review.splice(Number(b.dataset.reject),1)[0];data.matchDecisions??={};data.matchDecisions[decisionKey(e)]='exclude';save();}});
document.addEventListener('change',e=>{if(!editing)return;const el=e.target;if(el.dataset.vol){data.members.find(m=>m.id===el.dataset.vol).volunteer=el.value;save();}if(el.dataset.note){data.members.find(m=>m.id===el.dataset.note).note=el.value;save();}if(el.dataset.assign&&el.value){const s=data.shifts.find(s=>s.id===el.dataset.assign);if(s.members.length<s.capacity&&!s.members.includes(el.value))s.members.push(el.value);save();}});
$('search').oninput=renderRoster;
function addMember(name){name=name.trim().replace(/\s+/g,' ');if(!data.members.some(m=>m.id===key(name)))data.members.push({id:key(name),name,volunteer:'none',note:''});data.members.sort((a,b)=>a.name.localeCompare(b.name));}
$('addRider').onclick=()=>$('riderDialog').showModal();$('riderForm').onsubmit=e=>{e.preventDefault();const name=$('riderName').value.trim();if(!name)return;if(data.members.some(m=>m.id===key(name)))return toast('This rider is already on the roster.');addMember(name);save();$('riderDialog').close();e.target.reset();};
$('addShift').onclick=()=>$('shiftDialog').showModal();$('shiftForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(!String(f.get('title')).trim()||!String(f.get('time')).trim())return;data.shifts.push({id:crypto.randomUUID(),title:String(f.get('title')).trim(),time:String(f.get('time')).trim(),capacity:Number(f.get('capacity')),members:[]});save();$('shiftDialog').close();e.target.reset();};
const fields={brand:'Club / event name',brandSubtitle:'Brand subtitle',heading:'Page heading',description:'Page description',rosterHeading:'Roster heading',rosterDescription:'Roster description',footer:'Footer'};
$('designBtn').onclick=()=>{logoDraft=data.design.logo;$('logoInput').value='';$('designFields').innerHTML=Object.entries(fields).map(([f,l])=>'<label>'+l+'<input name="'+f+'" value="'+esc(data.design[f])+'" maxlength="200" required></label>').join('');$('colors').innerHTML=[['headerColor','Header'],['accentColor','Accent'],['backgroundColor','Background']].map(([f,l])=>'<label>'+l+'<input name="'+f+'" type="color" value="'+data.design[f]+'"></label>').join('');$('designDialog').showModal();};
$('logoInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>1000000||!['image/png','image/jpeg','image/webp'].includes(f.type)){e.target.value='';return toast('Choose a PNG, JPG or WebP smaller than 1 MB.');}logoDraft=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f);});};$('removeLogo').onclick=()=>{logoDraft='';$('logoInput').value='';toast('Logo will be removed when you save.');};$('designForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);for(const name of [...Object.keys(fields),'headerColor','accentColor','backgroundColor'])data.design[name]=String(f.get(name)).trim();data.design.logo=logoDraft;save();$('designDialog').close();};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
$('backup').onclick=()=>download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'race-dashboard-backup.json');
$('restore').onclick=()=>$('restoreFile').click();$('restoreFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>15000000)throw Error('Backup is too large.');const next=validate(JSON.parse(await file.text()));if(confirm('Replace this browser’s dashboard with this backup?')){data=next;save();toast('Backup restored.');}}catch(err){toast(err.message);}e.target.value='';};
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;text=text.replace(/^\uFEFF/,'');for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('CSV contains an unclosed quote.');row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows;}
function teamMatch(team){const t=key(team).replace(/\./g,'');if(/arizona state|northern arizona|\basu\b|\bnau\b/i.test(t))return 'other';return ['university of arizona','univeristy of arizona','university of arizona cycling','ua cycling','u of a','uofa','u of a cycling','uarizona','uarizona cycling'].includes(t)?'match':/arizona|\bua\b|wildcat|univ.*ariz/i.test(t)?'review':'other';}
function importCSV(text){const rows=parseCSV(text);if(rows.length<2)throw Error('CSV needs a header and at least one registration.');const heads=rows.shift().map(s=>key(s).replace(/[^a-z0-9]/g,''));const col=(...names)=>heads.findIndex(h=>names.includes(h)),n=col('name','fullname','rider','ridername'),first=col('firstname','first'),last=col('lastname','last'),team=col('team','teamname','club','clubteam'),cat=col('category','categoryname','race','racename'),date=col('date','entrydate','registrationdate');if(team<0||cat<0||(n<0&&(first<0||last<0)))throw Error('Required columns: Name (or First Name + Last Name), Team, Category.');const result={entries:[],review:[],ignored:0},seen=new Set();for(const r of rows){const name=(n>=0?r[n]:[r[first],r[last]].join(' '))?.trim(),category=r[cat]?.trim();if(!name||!category)throw Error('Every registration must have a name and category.');const e={name,team:r[team]?.trim()||'',category,date:date<0?'':r[date]||''};if(name.length>100||e.team.length>300||category.length>300)throw Error('A CSV field is too long.');const signature=key(name)+'|'+key(category);if(seen.has(signature))continue;seen.add(signature);const match=teamMatch(e.team);if(match==='match')result.entries.push(e);else if(match==='review')result.review.push(e);else result.ignored++;}return result;}
$('csvBtn').onclick=()=>{pendingCSV=null;$('csvFile').value='';$('csvPreview').hidden=true;$('confirmCSV').disabled=true;$('csvDialog').showModal();};$('csvFile').onchange=async e=>{pendingCSV=null;$('confirmCSV').disabled=true;try{const f=e.target.files[0];if(!f)return;if(f.size>10000000)throw Error('CSV must be smaller than 10 MB.');pendingCSV=importCSV(await f.text());$('csvPreview').hidden=false;$('csvPreview').textContent=pendingCSV.entries.length+' matched entries · '+pendingCSV.review.length+' to review · '+pendingCSV.ignored+' excluded. Your previous registration snapshot will be replaced.';$('confirmCSV').disabled=false;}catch(err){toast(err.message);}};$('confirmCSV').onclick=()=>{if(!pendingCSV)return;if(!pendingCSV.entries.length&&!confirm('No confirmed team entries were found. Clear the current registration snapshot?'))return;data.entries=pendingCSV.entries;data.review=pendingCSV.review;data.entries.forEach(e=>addMember(e.name));data.source='BikeReg CSV imported '+new Date().toLocaleString();save();$('csvDialog').close();toast('Registration snapshot updated. Review any uncertain team matches.');};

// Authentication and shared state. Authorization is enforced again in Postgres.
let client=null, officer=false, sessionUser=null, sharedVersion=null, dirty=false, saving=false, loadingShared=false, conflict=false;
let latestRegistrations={eventId:'76688',entries:seed.entries,review:seed.review,syncedAt:seed.syncedAt};
function decisionKey(e){return JSON.stringify([key(e.name),key(e.team)]);}
function sharedPayload(){return structuredClone({members:data.members,shifts:data.shifts,design:data.design,matchDecisions:data.matchDecisions||{}});}
function status(message){$('connectionStatus').textContent=message;}
function updateControls(){
  $('signOut').hidden=!sessionUser;
  $('saveOnline').hidden=!officer; $('saveOnline').disabled=!dirty||saving||conflict||sharedVersion===null;
  $('saveOnline').textContent=saving?'Saving…':dirty?'Save changes':'All changes saved';
  $('reloadShared').hidden=!officer;
  $('editToggle').textContent=officer?(editing?'Close officer tools':'Open officer tools'):'Officer sign in';
  $('saveState').textContent=conflict?'Another officer saved changes. Export your draft backup, then reload the shared version.':dirty?'Unsaved changes. Click Save changes to update the public dashboard.':'Changes are shared online after you click Save changes.';
  document.querySelectorAll('.editorOnly button,.editorOnly input,.editorOnly select,[data-vol],[data-note]').forEach(e=>e.disabled=false);
  if(saving)document.querySelectorAll('.editorOnly button,.editorOnly input,.editorOnly select,[data-vol],[data-note],[data-assign],[data-remove],[data-delete-shift]').forEach(e=>e.disabled=true);
  $('editToggle').disabled=saving; $('signOut').disabled=saving; $('reloadShared').disabled=saving;
}
function applyRegistrations(snapshot){
  if(snapshot.eventId!=='76688'||!Array.isArray(snapshot.entries)||!snapshot.entries.length||!Array.isArray(snapshot.review)||!Number.isFinite(Date.parse(snapshot.syncedAt)))throw Error('Invalid registration feed.');
  const candidate=structuredClone(data),decisions=data.matchDecisions||{};
  candidate.entries=[...snapshot.entries];candidate.review=[];
  for(const e of snapshot.review){const choice=decisions[decisionKey(e)];if(choice==='include')candidate.entries.push(e);else if(choice!=='exclude')candidate.review.push(e);}
  candidate.syncedAt=snapshot.syncedAt;candidate.source='BikeReg updated '+new Date(snapshot.syncedAt).toLocaleString();
  validate(candidate);data=candidate;data.entries.forEach(e=>addMember(e.name));latestRegistrations=structuredClone(snapshot);render();
}
let refreshing=false;
async function refreshRegistrations(){
  if(location.protocol==='file:'||refreshing||saving||document.activeElement?.matches('[data-note], [data-vol], [data-assign]'))return;refreshing=true;
  try{const response=await fetch(new URL('registrations.json',location.href),{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('No feed');const next=await response.json();if(next.syncedAt!==latestRegistrations.syncedAt)applyRegistrations(next);}
  catch(e){$('source').textContent=data.source+' · Registration feed unavailable. Showing the last saved registrations.';}
  finally{refreshing=false;}
}
function applyShared(row){
  const candidate={...data,...row.state};validate(candidate);
  if(!Number.isSafeInteger(row.version))throw Error('Invalid shared version.');
  data=candidate;sharedVersion=row.version;applyRegistrations(latestRegistrations);
}
async function loadShared(force=false){
  if(!client||loadingShared||saving||dirty&&!force)return false;
  loadingShared=true;
  try{const {data:row,error}=await client.from('dashboard_state').select('state,version,updated_at').eq('id','76688').single();if(error)throw error;
    // A draft may have started while this request was in flight.
    if(dirty&&!force)return false;
    if(row.version!==sharedVersion||force)applyShared(row);
    if(force){dirty=false;conflict=false;}
    status('Live dashboard · Officer changes refresh every 30 seconds');updateControls();return true;
  }catch(e){status('Shared data unavailable. Showing the last loaded dashboard. '+(officer?'Check setup or retry before editing.':''));return false;}
  finally{loadingShared=false;}
}
async function checkAccess(){
  if(!client)return;
  const {data:result,error}=await client.auth.getUser();
  const wasOfficer=officer,previousUser=sessionUser?.id;sessionUser=error?null:result.user;officer=false;
  if(sessionUser){const {data:allowed,error:roleError}=await client.rpc('is_dashboard_officer');officer=!roleError&&allowed===true;}
  if(!officer){editing=false;if(wasOfficer&&dirty){toast('Editing access ended. Your unsaved draft has not been published. Export it before reloading.');$('draftRecovery').hidden=false;}}
  if(wasOfficer!==officer||previousUser!==sessionUser?.id)render();
}
async function saveOnline(){
  if(!officer||!dirty||saving||conflict||sharedVersion===null)return;
  saving=true;render();status('Saving officer changes…');
  try{validate(data);const {data:row,error}=await client.rpc('save_dashboard',{p_state:sharedPayload(),p_expected_version:sharedVersion});if(error)throw error;
    applyShared(row);dirty=false;conflict=false;status('Saved online. Other visitors will see changes within 30 seconds.');toast('Changes saved for everyone.');
  }catch(e){if(e.code==='40001'){conflict=true;status('Another officer updated the dashboard. Export your draft, then reload shared data.');}else{status('Save failed. Your draft is still open; nothing was confirmed saved.');}toast(e.message||'Could not save. Please retry.');}
  finally{saving=false;render();}
}
$('saveOnline').onclick=saveOnline;
$('reloadShared').onclick=async()=>{if(dirty&&!confirm('Discard your unsaved draft and load the shared dashboard? Export a backup first if you need to keep it.'))return;await loadShared(true);};
$('editToggle').onclick=()=>{if(officer){if(sharedVersion===null)return toast('Load the shared dashboard before editing.');editing=!editing;render();}else{$('loginMessage').textContent=client?'Sign in with your approved officer account.':'Login needs setup. Add your Supabase URL and publishable key to config.js, then run the included SQL setup.';$('loginDialog').showModal();}};
$('loginForm').onsubmit=async e=>{e.preventDefault();if(!client)return;$('loginSubmit').disabled=true;$('loginMessage').textContent='Signing in…';
  try{const {error}=await client.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error)throw error;await checkAccess();
    if(!officer){$('loginMessage').textContent='This account has not been granted officer access. Ask the dashboard owner to add it.';return;}
    if(!await loadShared()){ $('loginMessage').textContent='Signed in, but shared data could not load. Check the database setup and try again.';return; }
    editing=true;$('loginDialog').close();$('loginPassword').value='';render();
  }catch(err){$('loginMessage').textContent='Sign-in failed. Check your email and password, then try again.';}
  finally{$('loginSubmit').disabled=false;}
};
$('forgotPassword').onclick=async()=>{if(!client)return;if(!$('loginEmail').reportValidity())return;$('forgotPassword').disabled=true;try{const url=new URL(location.href);url.hash='';url.search='';const {error}=await client.auth.resetPasswordForEmail($('loginEmail').value.trim(),{redirectTo:url.href});if(error)throw error;$('loginMessage').textContent='If the account exists, a password reset link will be emailed to you.';}catch(e){$('loginMessage').textContent='Could not send a reset link. Ask the owner to check email delivery settings.';}finally{$('forgotPassword').disabled=false;}};
$('passwordForm').onsubmit=async e=>{e.preventDefault();if($('newPassword').value!==$('confirmPassword').value){$('passwordMessage').textContent='Passwords do not match.';return;}$('passwordSubmit').disabled=true;try{const {error}=await client.auth.updateUser({password:$('newPassword').value});if(error)throw error;e.target.reset();$('passwordDialog').close();toast('Password updated.');await checkAccess();}catch(e){$('passwordMessage').textContent=e.message||'Could not update password.';}finally{$('passwordSubmit').disabled=false;}};
$('signOut').onclick=async()=>{if(dirty&&!confirm('Sign out and discard unsaved changes?'))return;const {error}=await client.auth.signOut({scope:'local'});if(error)return toast('Could not sign out. Please retry.');dirty=false;conflict=false;editing=false;officer=false;sessionUser=null;document.querySelectorAll('dialog[open]').forEach(d=>d.close());await loadShared(true);render();toast('Signed out.');};
$('draftBackup').onclick=()=>download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'unsaved-dashboard-draft.json');
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
async function boot(){
  render();
  const config=window.DASHBOARD_CONFIG||{};
  if(!config.supabaseUrl||!config.supabaseKey){status('Public preview · Officer login needs Supabase setup (see README).');refreshRegistrations();return;}
  try{const url=new URL(config.supabaseUrl);if(url.protocol!=='https:'||!window.supabase)throw Error('Invalid configuration');client=window.supabase.createClient(url.href,config.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
    client.auth.onAuthStateChange((event)=>{setTimeout(async()=>{if(event==='PASSWORD_RECOVERY'){$('passwordMessage').textContent='Choose your new password.';$('passwordDialog').showModal();}await checkAccess();},0);});
    await Promise.all([loadShared(),checkAccess()]);
    if(location.hash==='#login')$('editToggle').click();
  }catch(e){status('Login setup could not load. Check config.js and your Supabase project.');}
  refreshRegistrations();
}
boot();
setInterval(()=>{if(!document.hidden){loadShared();checkAccess();}},30000);
setInterval(()=>{if(!document.hidden)refreshRegistrations();},60000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden){loadShared();refreshRegistrations();checkAccess();}});
